params={
    'enc_type': 'lstm',
    'dec_type': 'lstm',
    'ni': 200,
    'nz': 16,
    'enc_nh': 512,
    'dec_nh': 512,
    'dec_dropout_in': 0.5,
    'dec_dropout_out': 0.5,
    'dec_dropout': 0.5,
    'batch_size': 64,
    'epochs': 200,
    'test_nepoch': 5,
    'train_data': 'datasets/short_yelp_data/short_yelp.train.txt',
    'val_data': 'datasets/short_yelp_data/short_yelp.valid.txt',
    'test_data': 'datasets/short_yelp_data/short_yelp.test.txt',
    'vocab_file': 'datasets/short_yelp_data/vocab.txt',
    "label": True,
}
